name: Spring cap-project-backend CI with SonarQube-Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test-sonarqube:
    name: Build, Test and SonarQube Scan
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Verify Java
        run: java -version

      - name: Verify Maven
        run: mvn -version


      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          sonar-scanner \
            -Dsonar.scanner.skipJreProvisioning=true \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN
